package com.thaumcraftmodern.registry;

import com.google.common.collect.ImmutableSet;
import com.thaumcraftmodern.ThaumcraftModern;
import com.thaumcraftmodern.aura.PrimalAspect;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.entity.ai.village.poi.PoiType;
import net.minecraft.world.entity.npc.VillagerProfession;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.trading.MerchantOffer;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.event.village.VillagerTradesEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.Set;

/**
 * Modern equivalents of the TC4 village thaumaturge and banker NPC roles.
 * Their workstations deliberately use already-playable Thaumcraft blocks, so
 * villagers generated by vanilla villages can acquire the professions too.
 */
@Mod.EventBusSubscriber(
        modid = ThaumcraftModern.MOD_ID,
        bus = Mod.EventBusSubscriber.Bus.FORGE
)
public final class ModVillagers {
    public static final DeferredRegister<PoiType> POI_TYPES =
            DeferredRegister.create(
                    ForgeRegistries.POI_TYPES,
                    ThaumcraftModern.MOD_ID
            );
    public static final DeferredRegister<VillagerProfession> PROFESSIONS =
            DeferredRegister.create(
                    ForgeRegistries.VILLAGER_PROFESSIONS,
                    ThaumcraftModern.MOD_ID
            );

    private static final ResourceKey<PoiType> THAUMATURGE_POI_KEY =
            ResourceKey.create(
                    Registries.POINT_OF_INTEREST_TYPE,
                    id("thaumaturge")
            );
    private static final ResourceKey<PoiType> BANKER_POI_KEY =
            ResourceKey.create(
                    Registries.POINT_OF_INTEREST_TYPE,
                    id("thaumic_banker")
            );

    public static final RegistryObject<PoiType> THAUMATURGE_POI =
            POI_TYPES.register(
                    "thaumaturge",
                    () -> poiFor(ModBlocks.RESEARCH_TABLE.get())
            );
    public static final RegistryObject<PoiType> BANKER_POI =
            POI_TYPES.register(
                    "thaumic_banker",
                    () -> poiFor(ModBlocks.ARCANE_WORKBENCH.get())
            );

    public static final RegistryObject<VillagerProfession> THAUMATURGE =
            PROFESSIONS.register(
                    "thaumaturge",
                    () -> new VillagerProfession(
                            "thaumaturge",
                            holder -> holder.is(THAUMATURGE_POI_KEY),
                            holder -> holder.is(THAUMATURGE_POI_KEY),
                            ImmutableSet.of(),
                            ImmutableSet.of(),
                            SoundEvents.VILLAGER_WORK_LIBRARIAN
                    )
            );
    public static final RegistryObject<VillagerProfession> THAUMIC_BANKER =
            PROFESSIONS.register(
                    "thaumic_banker",
                    () -> new VillagerProfession(
                            "thaumic_banker",
                            holder -> holder.is(BANKER_POI_KEY),
                            holder -> holder.is(BANKER_POI_KEY),
                            ImmutableSet.of(),
                            ImmutableSet.of(),
                            SoundEvents.VILLAGER_WORK_CARTOGRAPHER
                    )
            );

    private ModVillagers() {
    }

    public static void register(IEventBus modBus) {
        POI_TYPES.register(modBus);
        PROFESSIONS.register(modBus);
    }

    @SubscribeEvent
    public static void addTrades(VillagerTradesEvent event) {
        if (event.getType() == THAUMATURGE.get()) {
            event.getTrades().get(1).add(sells(ModItems.QUICKSILVER.get(), 3, 2, 12, 2));
            event.getTrades().get(1).add(buys(ModItems.AMBER.get(), 4, 1, 12, 2));
            event.getTrades().get(2).add(sells(ModItems.MANA_BEAN.get(), 4, 1, 8, 10));
            event.getTrades().get(2).add(sells(ModItems.KNOWLEDGE_FRAGMENT.get(), 6, 1, 6, 10));
            event.getTrades().get(3).add(sells(ModItems.GREATWOOD_SAPLING.get(), 8, 1, 4, 20));
            event.getTrades().get(4).add(sellsRandomAspectRing());
            event.getTrades().get(4).add(sellsRandomCost(
                    ModItems.VIS_STONE.get(), 5, 7, 1, 4, 30));
            event.getTrades().get(4).add(sells(ModItems.SILVERWOOD_SAPLING.get(), 16, 1, 2, 30));
        } else if (event.getType() == THAUMIC_BANKER.get()) {
            event.getTrades().get(1).add(buys(Items.GOLD_INGOT, 2, 3, 16, 2));
            event.getTrades().get(1).add(sells(ModItems.GOLD_COIN.get(), 1, 4, 16, 2));
            event.getTrades().get(2).add(buys(ModItems.GOLD_COIN.get(), 8, 2, 16, 10));
            event.getTrades().get(3).add(buys(ModItems.AMBER.get(), 3, 2, 12, 20));
        }
    }

    private static PoiType poiFor(Block block) {
        Set<net.minecraft.world.level.block.state.BlockState> states =
                ImmutableSet.copyOf(
                        block.getStateDefinition().getPossibleStates()
                );
        return new PoiType(states, 1, 1);
    }

    private static net.minecraft.world.entity.npc.VillagerTrades.ItemListing sells(
            net.minecraft.world.level.ItemLike item,
            int emeralds,
            int count,
            int maxUses,
            int xp
    ) {
        return (trader, random) -> new MerchantOffer(
                new ItemStack(Items.EMERALD, emeralds),
                new ItemStack(item, count),
                maxUses,
                xp,
                0.05F
        );
    }

    private static net.minecraft.world.entity.npc.VillagerTrades.ItemListing buys(
            net.minecraft.world.level.ItemLike item,
            int count,
            int emeralds,
            int maxUses,
            int xp
    ) {
        return (trader, random) -> new MerchantOffer(
                new ItemStack(item, count),
                new ItemStack(Items.EMERALD, emeralds),
                maxUses,
                xp,
                0.05F
        );
    }

    private static net.minecraft.world.entity.npc.VillagerTrades.ItemListing
            sellsRandomAspectRing() {
        return (trader, random) -> {
            PrimalAspect aspect = PrimalAspect.ordered().get(
                    random.nextInt(PrimalAspect.ordered().size()));
            int emeralds = 5 + random.nextInt(3);
            return new MerchantOffer(
                    new ItemStack(Items.EMERALD, emeralds),
                    new ItemStack(ModItems.ASPECT_RINGS.get(aspect).get()),
                    4,
                    30,
                    0.05F
            );
        };
    }

    private static net.minecraft.world.entity.npc.VillagerTrades.ItemListing
            sellsRandomCost(net.minecraft.world.level.ItemLike item,
            int minimumEmeralds, int maximumEmeralds, int count,
            int maxUses, int xp) {
        return (trader, random) -> new MerchantOffer(
                new ItemStack(Items.EMERALD, minimumEmeralds
                        + random.nextInt(maximumEmeralds - minimumEmeralds + 1)),
                new ItemStack(item, count),
                maxUses,
                xp,
                0.05F
        );
    }

    private static ResourceLocation id(String path) {
        return new ResourceLocation(
                ThaumcraftModern.MOD_ID,
                path
        );
    }
}
